[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Business Communications: Techniques and Strategies for More Effective and Engaging Written Communications with Technology"
